services:
  audiobookbay-rd:
    build: .
    image: audiobookbay-automated-rd:latest
    ports:
      - "5078:5078"
    container_name: audiobookbay-automated-rd
    environment:
      - REAL_DEBRID_API_TOKEN=${REAL_DEBRID_API_TOKEN:-}
      - ABB_HOSTNAME=${ABB_HOSTNAME:-audiobookbay.lu}
      - PAGE_LIMIT=${PAGE_LIMIT:-5}
      - DATABASE_PATH=/data/audiobooks.db
      - FLASK_PORT=5078
    volumes:
      - ./data:/data
    env_file:
      - path: .env
        required: false
